# Generated by Django 5.1.6 on 2025-02-11 15:46

import ckeditor.fields
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Kategori Adı')),
            ],
            options={
                'verbose_name': 'Kategori',
                'verbose_name_plural': 'Kategoriler',
            },
        ),
        migrations.CreateModel(
            name='RandevuSaati',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saat', models.TimeField(verbose_name='Saat')),
                ('bitis_saati', models.TimeField(verbose_name='Bitiş Saati')),
            ],
            options={
                'verbose_name': 'Randevu Saati',
                'verbose_name_plural': 'Randevu Saatleri',
                'ordering': ['saat'],
            },
        ),
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Kurs Adı')),
                ('description', ckeditor.fields.RichTextField(verbose_name='Açıklama')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Fiyat')),
                ('is_active', models.BooleanField(default=True, verbose_name='Aktif mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Güncellenme Tarihi')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='courses', to='courses.category', verbose_name='Kategori')),
            ],
            options={
                'verbose_name': 'Kurs',
                'verbose_name_plural': 'Kurslar',
            },
        ),
        migrations.CreateModel(
            name='RandevuSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tarih', models.DateField(verbose_name='Tarih')),
                ('is_available', models.BooleanField(default=True, verbose_name='Müsait mi?')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='Kurs')),
                ('randevu_saati', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.randevusaati', verbose_name='Randevu Saati')),
            ],
            options={
                'verbose_name': 'Randevu Slotu',
                'verbose_name_plural': 'Randevu Slotları',
                'ordering': ['tarih', 'randevu_saati'],
                'unique_together': {('course', 'tarih', 'randevu_saati')},
            },
        ),
        migrations.CreateModel(
            name='Randevu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(max_length=100, verbose_name='Ad Soyad')),
                ('telefon', models.CharField(max_length=15, verbose_name='Telefon')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('slot', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='courses.randevuslot', verbose_name='Randevu Slotu')),
            ],
            options={
                'verbose_name': 'Randevu',
                'verbose_name_plural': 'Randevular',
                'ordering': ['-created_at'],
            },
        ),
    ]
