# Generated by Django 5.1.6 on 2025-02-11 15:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randevuslot',
            name='randevu_saati',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.randevusaati', verbose_name='Randevu Saati'),
        ),
    ]
