# Generated by Django 5.1.6 on 2025-02-11 16:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_randevuslot_randevu_saati'),
    ]

    operations = [
        migrations.AddField(
            model_name='randevu',
            name='not_bilgisi',
            field=models.TextField(blank=True, null=True, verbose_name='Not'),
        ),
        migrations.CreateModel(
            name='BilgiTalebi',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad_soyad', models.CharField(max_length=100, verbose_name='Ad Soyad')),
                ('telefon', models.CharField(max_length=15, verbose_name='Telefon')),
                ('not_bilgisi', models.TextField(blank=True, null=True, verbose_name='Not')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Oluşturulma Tarihi')),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.course', verbose_name='Kurs')),
            ],
            options={
                'verbose_name': 'Bilgi Talebi',
                'verbose_name_plural': 'Bilgi Talepleri',
                'ordering': ['-created_at'],
            },
        ),
    ]
