# Generated by Django 5.1.6 on 2025-02-11 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_randevu_not_bilgisi_bilgitalebi'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='randevuslot',
            options={'ordering': ['tarih'], 'verbose_name': 'Randevu Slotu', 'verbose_name_plural': 'Randevu Slotları'},
        ),
        migrations.AlterUniqueTogether(
            name='randevuslot',
            unique_together={('course', 'tarih')},
        ),
        migrations.AddField(
            model_name='randevuslot',
            name='randevu_saatleri',
            field=models.ManyToManyField(to='courses.randevusaati', verbose_name='Randevu Saatleri'),
        ),
        migrations.RemoveField(
            model_name='randevuslot',
            name='randevu_saati',
        ),
    ]
