# Generated by Django 5.1.6 on 2025-02-11 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_randevuslot_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='randevuslot',
            name='is_available',
        ),
        migrations.AddField(
            model_name='randevu',
            name='randevu_saati',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='courses.randevusaati', verbose_name='Randevu Saati'),
        ),
        migrations.AlterField(
            model_name='randevu',
            name='slot',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.randevuslot', verbose_name='Randevu Slotu'),
        ),
    ]
