# Generated by Django 5.1.6 on 2025-02-11 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0005_remove_randevuslot_is_available_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='randevu',
            name='randevu_saati',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.randevusaati', verbose_name='Randevu Saati'),
        ),
    ]
